"""Rundeck job and resources sync — artifact emission."""

from __future__ import annotations

import sys
from pathlib import Path

from src.api import rundeck_api
from src.context import ProvisionContext
from src.inventory import hosts, resources_gen
from src.rundeck import job_gen
from src.sync.uptime_sync import PingRecord
from src.utils.util import log


def _emit_resources(
    ctx: ProvisionContext,
    jg: job_gen.JobGenDefaults,
    pings: list[PingRecord],
    workdir: str,
) -> None:
    """Write nodes.yaml staging file and push to repo or API."""
    cfg = ctx.cfg
    resources_yaml = str(Path(workdir) / "nodes.yaml")
    resources_gen.build_resources_yaml(ctx, jg, pings, resources_yaml)
    if cfg.is_dry_run():
        content = Path(resources_yaml).read_text(encoding="utf-8")
        log(
            f"dry_run: would write {len(content.splitlines())} lines to "
            f"{rundeck_api.resources_dest_path(cfg.scm_base_dir, cfg.rundeck_resources_path)}"
        )
        print("\n".join(content.splitlines()[:80]), file=sys.stderr)
    else:
        rundeck_api.write_resources_to_repo(
            resources_yaml,
            cfg.scm_base_dir,
            cfg.rundeck_resources_path,
        )


def _emit_per_check_jobs(ctx: ProvisionContext, jg: job_gen.JobGenDefaults) -> list[str]:
    """Emit per-check job YAML files; return list of check ids emitted."""
    cfg = ctx.cfg
    checks_meta = ctx.ensure_checks_meta()
    job_check_ids: list[str] = []
    for check_id in ctx.checks.check_ids:
        if not check_id:
            continue
        job_check_ids.append(check_id)
        meta = checks_meta[check_id]
        name = meta.get("name") or f"houston - {check_id}"
        desc = (
            (meta.get("desc") or "Auto-generated by houston-provision.")
            .replace("\n", " ")
            .replace("'", "&apos;")
        )
        executor = meta["executor"]
        if cfg.is_dry_run():
            log(f"dry_run: would emit per-check {check_id}.yaml (executor={executor})")
        else:
            job_gen.emit_per_check(
                cfg,
                jg,
                check_id,
                name,
                desc,
                executor,
                catalog_spec=ctx.checks.spec(check_id),
            )
    return job_check_ids


def _emit_per_group_jobs(ctx: ProvisionContext, jg: job_gen.JobGenDefaults) -> list[str]:
    """Emit per-group job YAML files; return list of group ids emitted."""
    cfg = ctx.cfg
    group_ids_list: list[str] = []
    for gid in hosts.group_ids(ctx.inv, ctx.indexes):
        if not gid:
            continue
        group_ids_list.append(gid)
        check_ids = ctx.checks.group_check_ids(gid)
        if not check_ids:
            log(f"group {gid} has no catalog checks; skipping per-group job")
            continue
        tags = hosts.group_tags(ctx.inv, gid)
        first_tag = tags[0] if tags else gid
        desc = f"Auto-generated by houston-provision — parallel workflow for group {gid}."
        if cfg.is_dry_run():
            log(
                f"dry_run: would emit per-group {gid}.yaml "
                f"(checks={' '.join(check_ids)} tag={first_tag})"
            )
        else:
            job_gen.emit_per_group(cfg, jg, gid, first_tag, desc, check_ids)
    return group_ids_list


def emit_rundeck_artifacts(
    ctx: ProvisionContext,
    jg: job_gen.JobGenDefaults,
    pings: list[PingRecord],
    workdir: str,
) -> None:
    """Generate nodes.yaml, per-check and per-group Rundeck jobs."""
    _emit_resources(ctx, jg, pings, workdir)
    job_check_ids = _emit_per_check_jobs(ctx, jg)
    group_ids_list = _emit_per_group_jobs(ctx, jg)
    if not ctx.cfg.is_dry_run():
        job_gen.prune_dir(ctx.cfg, "per-check", job_check_ids)
        job_gen.prune_dir(ctx.cfg, "per-group", group_ids_list)
