"""Parse check script headers (# Name:, # Description:, etc.)."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any


def script_path(scm_base: str, check_id: str, executor_hint: str = "") -> Path:
    """Resolve the check script file path under SCM_BASE_DIR."""
    shell_path = Path(scm_base) / "check-shell" / f"{check_id}.sh"
    py_path = Path(scm_base) / "check-python" / f"{check_id}.py"
    if executor_hint == "python_bastion" and py_path.is_file():
        return py_path
    if executor_hint == "shell" and shell_path.is_file():
        return shell_path
    if py_path.is_file() and not shell_path.is_file():
        return py_path
    return shell_path


def parse_header(script_path: Path) -> dict[str, Any]:
    """Parse # Name:, # Description:, # Executor:, etc. from a check script header."""
    if not script_path.is_file():
        return {}
    name = desc = executor = ""
    in_header = True
    with script_path.open(encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#!"):
                continue
            if in_header and line.lstrip().startswith("#"):
                content = re.sub(r"^\s*#\s?", "", line).strip()
                if not content:
                    continue
                if content.startswith("Name:"):
                    name = content[5:].strip()
                elif content.startswith("Description:"):
                    part = content[12:].strip()
                    desc = part if not desc else f"{desc} {part}"
                elif content.startswith("Executor:"):
                    executor = content[9:].strip()
                continue
            in_header = False
    return {"name": name, "desc": desc, "executor": executor}


def _meta_from_script(abs_path: Path, fallback_id: str) -> dict[str, Any]:
    if not abs_path.is_file():
        raise FileNotFoundError(
            f"check {fallback_id}: script not found at {abs_path}"
        )
    raw = parse_header(abs_path)
    name = raw.get("name") or fallback_id
    desc = raw.get("desc") or "Auto-generated by houston-provision."
    executor = raw.get("executor") or ""
    if not executor:
        if abs_path.suffix == ".py":
            executor = "python"
        else:
            executor = "shell"
    return {"name": name, "desc": desc, "executor": executor}


def meta_for_path(scm_base: str, rel_path: str) -> dict[str, Any]:
    """Parse script headers for a repo-relative check path."""
    from src.inventory import paths

    check_id = paths.check_id_from_path(rel_path)
    abs_path = paths.resolve_check_path(scm_base, rel_path)
    return _meta_from_script(abs_path, check_id)


def meta_for_id(scm_base: str, check_id: str) -> dict[str, Any]:
    """Load metadata from the check script for a catalog check id."""
    path = script_path(scm_base, check_id)
    return _meta_from_script(path, check_id)
